stages:
  - checkout
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"  # Optional, helps cache Gradle dependencies

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

checkout:
  stage: checkout
  script:
    - echo "Checking out code from the repository..."
  only:
    - main
  before_script:
    - git clone https://github.com/GANWEIJIA/Java_Gradle_Responsive_Website.git .

build:
  stage: build
  script:
    - echo "Building the project using Gradle..."
    - ./gradlew clean build  # Adjust this based on your OS if not Windows
  only:
    - main
  when: on_success
  retry: 2  # Retry the job up to 2 times in case of failure

test:
  stage: test
  script:
    - echo "Running tests..."
    - ./gradlew test
  only:
    - main
  when: on_success
  retry: 2  # Retry the job up to 2 times in case of failure

after_script:
  - echo "Cleaning up workspace"
  - rm -rf $CI_PROJECT_DIR

