# GitLab CI configuration for Java Gradle Responsive Website project

# Define stages
stages:
  - build
  - test

# Variables
variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"  # Caches Gradle dependencies

# Cache configuration to speed up builds
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Build job
build:
  stage: build
  script:
    - echo "Starting the build..."
    - ./gradlew clean build  # Clean and build the project using Gradle
  only:
    - main  # Run this job only on the main branch
  artifacts:
    paths:
      - build/libs/  # Save the build artifacts for later use

# Test job
test:
  stage: test
  script:
    - echo "Running tests..."
    - ./gradlew test  # Run tests
  only:
    - main  # Run this job only on the main branch
  artifacts:
    when: always
    paths:
      - build/reports/tests/  # Save test reports as artifacts

# Clean up after the pipeline
after_script:
  - echo "Cleaning up workspace..."
  - rm -rf $CI_PROJECT_DIR
