name: CI Pipeline

# Trigger the workflow on push or pull request to main and development branches
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Checkout successful!"

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew.bat clean build
        shell: powershell
      - if: success()
        run: echo "Build successful!"
      - if: failure()
        run: echo "Build failed!"

      # Run the tests
      - name: Run tests with Gradle
        run: ./gradlew.bat test
        shell: powershell
      - if: success()
        run: echo "Tests executed successfully!"
      - if: failure()
        run: echo "Tests execution failed!"

      # Build Docker image and push to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/responsive-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/responsive-web:latest

      - if: success()
        run: echo "Docker image built and pushed successfully!"
      - if: failure()
        run: echo "Docker build or push failed!"

      # Deploy to a remote server (optional)
      - name: Deploy to Server
        if: github.ref == 'refs/heads/main'
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker pull ${{ secrets.DOCKER_USERNAME }}/responsive-web:latest
          docker stop my_app || true
          docker rm my_app || true
          docker run -d --name my_app -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/responsive-web:latest
          EOF
      - if: success()
        run: echo "Deployment successful!"
      - if: failure()
        run: echo "Deployment failed!"

      # Post build actions (e.g., clean up)
      - name: Clean up workspace
        run: git clean -fdx
        shell: bash
      - run: echo "Cleaning up workspace"
