stages:
  - checkout
  - build
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"  # Optional, helps cache Gradle dependencies

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

checkout:
  stage: checkout
  script:
    - echo "Checking out code from the repository..."
    - git clone https://github.com/BaKaLoVes/Java_Gradle_Responsive_Website.git .
  only:
    - main  # This ensures the job runs only on the 'main' branch

build:
  stage: build
  script:
    - echo "Building the project using Gradle..."
    - ./gradlew clean build  # Adjust this based on your OS if not Windows
  only:
    - main  # Runs only on the 'main' branch

test:
  stage: test
  script:
    - echo "Running tests..."
    - ./gradlew test
  only:
    - main  # Runs only on the 'main' branch

after_script:
  - echo "Cleaning up workspace"
  - rm -rf $CI_PROJECT_DIR
